sonar.projectKey=go-gateway
sonar.projectName=Go Gateway
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,coverage.html,*.html
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
